- name: Nginx and Games Deployment
  hosts: webservers
  become: yes
  tasks:
    - name: Installation Nginx
      ansible.builtin.apt:
        name: nginx
        state: present
        update_cache: yes
        cache_valid_time: 3600

    - name: Demarrer et activer Nginx
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: yes

    - name: Copier tous les fichiers web (Portail + Jeux Snake/Tetris) dans Nginx
      ansible.builtin.copy:
        src: ../files/
        dest: /var/www/html/
        owner: www-data
        group: www-data
        mode: '0644'
