name: 3. Pipeline Gitleaks Secrets

on:
  push:
    branches: [ "main", "TP-1" ]
  pull_request:
    branches: [ "main", "TP-1" ]

jobs:
  gitleaks-scan:
    name: Gitleaks sur ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, windows-2022, macos-14]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Code Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Gitleaks
        shell: bash
        run: |
          if [[ "${{ matrix.os }}" == "ubuntu-22.04" ]]; then
            wget -q https://github.com/gitleaks/gitleaks/releases/download/v8.18.2/gitleaks_8.18.2_linux_x64.tar.gz
            tar -xzf gitleaks_8.18.2_linux_x64.tar.gz gitleaks
            sudo mv gitleaks /usr/local/bin/
          elif [[ "${{ matrix.os }}" == "macos-14" ]]; then
            brew install gitleaks
          elif [[ "${{ matrix.os }}" == "windows-2022" ]]; then
            choco install gitleaks -y
          fi

      - name: Run Gitleaks
        id: gitleaks
        shell: bash
        continue-on-error: true
        run: |
          gitleaks detect --source . --verbose

      - name: Create Gitleaks Report
        if: always()
        shell: bash
        run: |
          if [ "${{ steps.gitleaks.outcome }}" == "success" ]; then
            MSG="🔑 GITLEAKS CLEAN ! Aucun leak de secret trouvé, zéro fuite beau gosse ! 😎"
            COLOR="#dcfce7"
          else
            MSG="🚨 ALERTE GITLEAKS ! Tu as laissé un secret ou un mot de passe dans le code !"
            COLOR="#fee2e2"
          fi

          echo "## Résultat Gitleaks (${{ matrix.os }})" >> $GITHUB_STEP_SUMMARY
          echo "$MSG" >> $GITHUB_STEP_SUMMARY

          cat <<EOF > rapport_gitleaks_${{ matrix.os }}.html
          <!DOCTYPE html>
          <html>
          <body style="font-family: Arial; padding: 20px;">
              <h2>Rapport Fuites de Secrets Gitleaks - ${{ matrix.os }}</h2>
              <div style="background-color: ${COLOR}; padding: 15px; border-radius: 8px; font-weight: bold;">
                  ${MSG}
              </div>
          </body>
          </html>
          EOF

      - name: Upload Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: rapport-gitleaks-${{ matrix.os }}
          path: rapport_gitleaks_${{ matrix.os }}.html
