name: CI Pipeline Security Check

on:
  push:
    branches: [ "main", "TP-1" ]
  pull_request:
    branches: [ "main", "TP-1" ]

jobs:
  security-audit:
    runs-on: ubuntu-22.04

    steps:
      # 1. Récupérer le code avec tout l'historique
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 2. Scanner le code avec Gitleaks
      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2

      # 3. Rendre le rapport téléchargeable sur GitHub Actions
      - name: Upload Report
        uses: actions/upload-artifact@v4
        if: always() # Génère le rapport même en cas d'échec
        with:
          name: rapport-securite-ci
          path: README.md
